### ISSUE TITLE
Javarosa 2.5.0 breaks data preloading

### ISSUE THREAD

**Issue by grzesiek2010** [opendatakit/javarosa#171]
I haven't been able to open a form with [data preloading](https://opendatakit.org/help/form-design/data-preloading/) since we updated javarosa to 2.5.0-SNAPSHOT version: https://github.com/opendatakit/collect/pull/1352/files

![screenshot_2017-08-18-12-51-05](https://user-images.githubusercontent.com/3276264/29457049-997f4288-8418-11e7-9c7a-3ff8f8121793.png)

Logs:
> E/FormLoaderTask: java.lang.NullPointerException: Attempt to invoke interface method 'void org.javarosa.core.model.instance.AbstractTreeElement.clearCaches()' on a null object reference
                                                                             at org.javarosa.xform.parse.XFormParser.parseDoc(XFormParser.java:497)
                                                                             at org.javarosa.xform.parse.XFormParser.parse(XFormParser.java:323)
                                                                             at org.javarosa.xform.util.XFormUtils.getFormFromInputStream(XFormUtils.java:79)
                                                                             at org.odk.collect.android.tasks.FormLoaderTask.doInBackground(FormLoaderTask.java:165)
                                                                             at org.odk.collect.android.tasks.FormLoaderTask.doInBackground(FormLoaderTask.java:73)
                                                                             at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                             at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                             at java.lang.Thread.run(Thread.java:818)

**Comment by lognaturel** [comment]
Thank you so much, @grzesiek2010! This is a big one that will block a new release.

@dcbriccetti Would be great for you to look at this one first when you come back to JR. Hopefully there's a failing test that can be written.

**Comment by dcbriccetti** [comment]
I’m looking at this now.

**Comment by lognaturel** [comment]
🙏 Thank you for catching this, @grzesiek2010 and for fixing, @dcbriccetti, it could have been a real scramble to fix if we had shipped this!

@yanokwa published a new snapshot and I have verified that Collect's `master` branch now supports CSV external data again.

**Comment by dcbriccetti** [comment]
>Thank you for catching this, @grzesiek2010

Indeed, thank you! You helped me preserve the illusion that I am a competent programmer. ;-)
