### ISSUE TITLE
FormEntryPrompt getLongText UnregisteredLocaleException

### ISSUE THREAD

**Issue by meSmashsta** [opendatakit/javarosa#364]
JavaRosa v1.x.x, Java v1.x.x, operating system
OS: Windows 10
Java: jdk1.8.0_172

#### Problem description
After pulling the **form** from a **downloadUrl** using **OkHttpClient**, I am unable to invoke `org.javarosa.form.api.FormEntryCaption#getLongText`, it crashes everytime.

It crashes in `case FormEntryController.EVENT_QUESTION:` specifically this line `String text = entry.getLongText();`

#### Steps to reproduce the problem
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        ...
        OkHttpClient client = new OkHttpClient();
        Request request = new Request.Builder()
                .url(url)
                .build();

        client.newCall(request).enqueue(new Callback() {
            ...
            @Override
            public void onResponse(Call call, Response response) throws IOException {
                InputStream is = response.body().byteStream();
                FormDef def = XFormUtils.getFormFromInputStream(is);
                FormEntryModel fem = new FormEntryModel(def);
                FormEntryController fec = new FormEntryController(fem);

                int event = fec.getModel().getEvent();
                moveForm(event, fec);
            }
        });

    // recursion. aims to print the question of each forms
    public void moveForm(int event, FormEntryController fec) {
        switch (event) {
            case FormEntryController.EVENT_BEGINNING_OF_FORM:
                Log.d(TAG, "BEGIN");
                moveForm(fec.stepToNextEvent(), fec);
                break;
            case FormEntryController.EVENT_END_OF_FORM:
                Log.d(TAG, "END");
                break;
            case FormEntryController.EVENT_QUESTION:
                Log.d(TAG, "QUESTION");
                FormEntryPrompt entry = fec.getModel().getQuestionPrompt();
                switch (entry.getControlType()) {
                    case Constants.DATATYPE_TEXT:
                        // it crashes here!
                        String text = entry.getLongText();
                        Log.d(TAG, "text: " + text);
                        break;
                }
                moveForm(fec.stepToNextEvent(), fec);
                break;
            case FormEntryController.EVENT_GROUP:
                Log.d(TAG, "GROUP");
                moveForm(fec.stepToNextEvent(), fec);
                break;
            case FormEntryController.EVENT_REPEAT:
                Log.d(TAG, "REPEAT");
                moveForm(fec.stepToNextEvent(), fec);
                break;
            case FormEntryController.EVENT_PROMPT_NEW_REPEAT:
                Log.d(TAG, "NEW REPEAT");
                break;
            default:
                Log.d(TAG, "NANI?!?!");
                break;
        }
    }

#### Expected behavior
All I'm trying to do is list out the questions inside of the downloaded form.

#### Other information 
I have been reading up ODK Collect on how they used JavaRosa, but it's been a week already, I'm so weary and tired.

**Crash**
    org.javarosa.core.util.UnregisteredLocaleException: Null locale when attempting to fetch text id: /a4SwhSWR5iTs3244BLLTaE/What_is_the_personal_ID_number:label;long
        at org.javarosa.core.services.locale.Localizer.getRawText(Localizer.java:548)
        at org.javarosa.form.api.FormEntryCaption.getIText(FormEntryCaption.java:197)
        at org.javarosa.form.api.FormEntryCaption.getQuestionText(FormEntryCaption.java:141)
        at org.javarosa.form.api.FormEntryCaption.getLongText(FormEntryCaption.java:85)
        at com.blazingmuffin.aqmrosa.ListQuestionActivity.moveForm(ListQuestionActivity.java:92)
        at com.blazingmuffin.aqmrosa.ListQuestionActivity.moveForm(ListQuestionActivity.java:99)
        at com.blazingmuffin.aqmrosa.ListQuestionActivity.moveForm(ListQuestionActivity.java:99)
        at com.blazingmuffin.aqmrosa.ListQuestionActivity.moveForm(ListQuestionActivity.java:80)
        at com.blazingmuffin.aqmrosa.ListQuestionActivity$1.onResponse(ListQuestionActivity.java:60)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)

**Comment by yanokwa** [comment]
If you are trying to step through an entire form, it might be easier to look at how we do it here: https://github.com/opendatakit/validate/blob/master/src/org/opendatakit/validate/FormValidator.java#L386

**Comment by meSmashsta** [comment]
Thanks @yanokwa. I'll keep you posted if ever I get it to work or not. Oh and would you please tell me something about this error? Have I missed configure it before accessing it?

**Comment by yanokwa** [comment]
I don't know about the specific error, but I'd recommend you start with the Validate class because it's a good way to start. https://github.com/nafundi/odk-codebook might also be helpful, but it's a little old these days.

**Comment by meSmashsta** [comment]
Thanks! I will take a look at that too.
