### ISSUE TITLE
Randomize cannot be used with a nodeset path

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/javarosa#384]
#### Software versions 
JavaRosa v2.12, Collect v1.18

#### Problem description
It seems like paths aren't allowed as a seed.

This works:
`<itemset nodeset="randomize(instance('opt_abcd')/root/item, 12345)">`

This fails:
`<itemset nodeset="randomize(instance('opt_abcd')/root/item, /rand/my_seed)">`

The error message I get is
```
java.lang.NumberFormatException: For input string: "/rand/my_seed"
	at java.lang.Long.parseLong(Long.java:432)
	at java.lang.Long.parseLong(Long.java:485)
	at org.javarosa.xform.parse.RandomizeHelper.parseSeed(RandomizeHelper.java:44)
	at org.javarosa.xform.parse.XFormParser.parseItemset(XFormParser.java:1321)
	at org.javarosa.xform.parse.XFormParser.parseControl(XFormParser.java:1000)
	at org.javarosa.xform.parse.XFormParser.parseControl(XFormParser.java:910)
	at org.javarosa.xform.parse.XFormParser.access$200(XFormParser.java:120)
	at org.javarosa.xform.parse.XFormParser$1$6.handle(XFormParser.java:242)
	at org.javarosa.xform.parse.XFormParser.parseElement(XFormParser.java:531)
	at org.javarosa.xform.parse.XFormParser.parseElement(XFormParser.java:540)
	at org.javarosa.xform.parse.XFormParser.parseElement(XFormParser.java:540)
	at org.javarosa.xform.parse.XFormParser.parseDoc(XFormParser.java:447)
	at org.javarosa.xform.parse.XFormParser.parse(XFormParser.java:358)
	at org.javarosa.xform.util.XFormUtils.getFormFromInputStream(XFormUtils.java:81)
	at org.odk.collect.android.tasks.FormLoaderTask.createFormDefFromCacheOrXml(FormLoaderTask.java:236)
	at org.odk.collect.android.tasks.FormLoaderTask.doInBackground(FormLoaderTask.java:126)
	at org.odk.collect.android.tasks.FormLoaderTask.doInBackground(FormLoaderTask.java:70)
	at android.os.AsyncTask$2.call(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
```

#### Steps to reproduce the problem
Load [rand.xml.zip](https://github.com/opendatakit/javarosa/files/2596539/rand.xml.zip) into Collect. Open it and it'll crash with the above error.

#### Expected behavior
A seed using the value at /rand/my_seed is loaded.

#### Other information 
This is urgent because it provides a workaround for https://github.com/XLSForm/pyxform/issues/238.

**Comment by yanokwa** [comment]
@ggalmazor, can you take at this when you get a moment?

**Comment by ggalmazor** [comment]
Sure!
