### ISSUE TITLE
Error evaluating field Double cannot be cast to String

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/javarosa#391]
#### Software versions 
JavaRosa master

#### Problem description
In the sample form, if you select any answer and swipe to the next question, you get a crash in Collect. 
`Error evaluating field 'Intencion_A': java.lang.Double cannot be cast to java.lang.String`

[Ejemplo.xlsx.zip](https://github.com/opendatakit/javarosa/files/2688436/Ejemplo.xlsx.zip)

```
org.odk.collect.android.exception.JavaRosaException: Error evaluating field 'Intencion_A': java.lang.Double cannot be cast to 
	at org.odk.collect.android.logic.FormController.answerQuestion(FormController.java:457)
	at org.odk.collect.android.logic.FormController.saveAllScreenAnswers(FormController.java:688)
	at org.odk.collect.android.activities.FormEntryActivity.saveAnswersForCurrentScreen(FormEntryActivity.java:1020)
	at org.odk.collect.android.activities.FormEntryActivity.showNextView(FormEntryActivity.java:1382)
	at org.odk.collect.android.activities.FormEntryActivity.onFling(FormEntryActivity.java:2613)
	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:656)
	at org.odk.collect.android.activities.FormEntryActivity.dispatchTouchEvent(FormEntryActivity.java:1357)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:398)
	at android.view.View.dispatchPointerEvent(View.java:12752)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5106)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4909)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4585)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4453)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4642)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4479)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4445)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4453)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4426)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7092)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7061)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7022)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7195)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:326)
	at android.os.Looper.loop(Looper.java:160)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.RuntimeException: Error evaluating field 'Intencion_A': java.lang.Double cannot be cast to java.lang.String
	at org.javarosa.core.model.LatestDagBase.evaluateTriggerable(LatestDagBase.java:139)
	at org.javarosa.core.model.LatestDagBase.doEvaluateTriggerables(LatestDagBase.java:63)
	at org.javarosa.core.model.Safe2014DagImpl.evaluateTriggerables(Safe2014DagImpl.java:366)
	at org.javarosa.core.model.Safe2014DagImpl.triggerTriggerables(Safe2014DagImpl.java:493)
	at org.javarosa.core.model.Safe2014DagImpl.triggerTriggerables(Safe2014DagImpl.java:469)
	at org.javarosa.core.model.FormDef.triggerTriggerables(FormDef.java:706)
	at org.javarosa.core.model.FormDef.setValue(FormDef.java:399)
	at org.javarosa.form.api.FormEntryController.commitAnswer(FormEntryController.java:158)
	at org.javarosa.form.api.FormEntryController.answerQuestion(FormEntryController.java:96)
	at org.odk.collect.android.logic.FormController.answerQuestion(FormController.java:455)
	... 35 more
Caused by: java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String
```

**Comment by ggalmazor** [comment]
I'm not sure about this issue. 

Setting a string value to the `range` question will make the `relevant` expression work without errors. This makes sense because the `select` function in the `relevant` expression is intended to be used with `select` and `select1` fields, which encode their answers as strings (xml serialized values). For ranges, it would make more sense to use a boolean expression like `field = 5` or even `field >= 5`, which works.

Here's a compilation of the tests I've made:

|  `relevant` | Set `"5"` (string value) | Set `5` (decimal value) |
| --- | --- | --- |
| (empty) | No error | No error |
| `selected( /Ejemplo/S2/Imagen_A, '5')` | No error - Question is shown | Cast error |
| `/Ejemplo/S2/Imagen_A = 5` | No error - Question is shown | No error - Question is shown |
| `/Ejemplo/S2/Imagen_A = '5'` | No error - Question is shown | No error - Question is shown |

**Comment by yanokwa** [comment]
Closing because I agree this isn't a bug. 

User facing discussion is at https://forum.opendatakit.org/t/error-evaluating-field/16772
