### ISSUE TITLE
Unrecognized top-level tag [setlocation] found

### ISSUE THREAD

**Issue by grzesiek2010** [opendatakit/javarosa#500]
#### Software versions 
JavaRosa v2.16.0

#### Problem description
https://console.firebase.google.com/project/api-project-322300403941/crashlytics/app/android:org.odk.collect.android/issues/a6f266f0ddb057f3073a47df66b2adaa?time=last-seven-days&sessionId=5DA456F2029700014203921D20B5CC4B_DNE_0_v2

`Caused by org.javarosa.xform.parse.XFormParseException: Unrecognized top-level tag [setlocation] found within <model>
    Problem found at nodeset: /html/head/model/setlocation
    With element <setlocation ref="/data/location" event="odk-instance-first-load"/>

       at org.javarosa.xform.parse.XFormParser.parseModel(XFormParser.java:685)
       at org.javarosa.xform.parse.XFormParser.access$500(XFormParser.java:123)
       at org.javarosa.xform.parse.XFormParser$2$1.handle(XFormParser.java:295)
       at org.javarosa.xform.parse.XFormParser.parseElement(XFormParser.java:590)
       at org.javarosa.xform.parse.XFormParser.parseElement(XFormParser.java:599)
       at org.javarosa.xform.parse.XFormParser.parseElement(XFormParser.java:599)
       at org.javarosa.xform.parse.XFormParser.parseDoc(XFormParser.java:479)
       at org.javarosa.xform.parse.XFormParser.parse(XFormParser.java:387)
       at org.javarosa.xform.util.XFormUtils.getFormFromFormXml(XFormUtils.java:123)
       at org.odk.collect.android.tasks.FormLoaderTask.createFormDefFromCacheOrXml(FormLoaderTask.java:244)
       at org.odk.collect.android.tasks.FormLoaderTask.doInBackground(FormLoaderTask.java:147)
       at org.odk.collect.android.tasks.FormLoaderTask.doInBackground(FormLoaderTask.java:68)
       at android.os.AsyncTask$2.call(AsyncTask.java:304)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)`

#### Steps to reproduce the problem
Use a sample form attached here: https://github.com/opendatakit/collect/pull/3175

#### Other information 
`setlocation` has been renamed to `setgeopoint` https://github.com/opendatakit/javarosa/commit/24c91ea0b47b2ab7aaaf05404a812856246b1539 but we don't provide backward compatibility.

**Comment by grzesiek2010** [comment]
I think we don't need to provide backward compatibility here but we should catch the exception and display an appropriate message. Do you agree @lognaturel?

**Comment by grzesiek2010** [comment]
I think you will agree so I created a pr https://github.com/opendatakit/collect/pull/3396 if not let me know.

**Comment by lognaturel** [comment]
Very good conversation that you had with yourself. 😉 I do agree.

JavaRosa is doing the right thing so I'll close this. I think it's fine not to have an issue for opendatakit/collect#3396 -- its behavior is very clear.
