### ISSUE TITLE
current() without a path doesn't work

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/javarosa#510]
[This form](https://docs.google.com/spreadsheets/d/12vcVPGGewjtqnf6hmKEFiPZN_I2d36CKJ-zhbZfWbpI/edit#gid=0) has the following predicate:

```xml
name = current()/. or not(selected(join(" ", /select-no-duplicates/repeat/option), name))
```

It should be possible to use `current()` without a path but we get:

```java
org.javarosa.xpath.XPathUnhandledException: XPath evaluation: cannot handle function 'current'
	at org.javarosa.xpath.expr.XPathFuncExpr.eval(XPathFuncExpr.java:486)
	at org.javarosa.xpath.expr.XPathEqExpr.eval(XPathEqExpr.java:56)
	at org.javarosa.xpath.expr.XPathBoolExpr.eval(XPathBoolExpr.java:43)
	at org.javarosa.core.model.condition.EvaluationContext.expandReferenceAccumulator(EvaluationContext.java:308)
	at org.javarosa.core.model.condition.EvaluationContext.expandReference(EvaluationContext.java:217)
	at org.javarosa.core.model.condition.EvaluationContext.expandReference(EvaluationContext.java:186)
	at org.javarosa.xpath.expr.XPathPathExprEval.eval(XPathPathExprEval.java:34)
	at org.javarosa.xpath.expr.XPathPathExpr.eval(XPathPathExpr.java:210)
	at org.javarosa.xpath.XPathConditional.evalNodeset(XPathConditional.java:93)
	at org.javarosa.core.model.FormDef.populateDynamicChoices(FormDef.java:1017)
	at org.javarosa.form.api.FormEntryPrompt.getSelectChoices(FormEntryPrompt.java:235)
```

**Comment by abdulazizali77** [comment]
hi @lognaturel id like to give this a shot!

**Comment by lognaturel** [comment]
That would be amazing, @abdulazizali77! I haven't looked at a possible solution yet so I don't have a sense of whether it requires a lot of context or is hard. The first thing would be to get a failing test together and even just that would be a great contribution.

**Comment by abdulazizali77** [comment]
@lognaturel apologies for the delay, ive finally gotten around to understanding this a bit but have not yet managed to replicate it! Im not sure what youre invoking to get the stack trace, so bear with me. When we call the path with `Scenario` like so its all fine and dandy
```
Scenario scenario = Scenario.init("510-select-no-duplicates-original.xml");
List<SelectChoice> choices= scenario.choicesOf("/data/repeat[0]/option");
```
But when we call it with bare `FormDef` im not sure how youre getting the formindex to instantiate the `FormEntryPrompt`

```
FormParseInit fpi = new FormParseInit(r("510-select-no-duplicates-original.xml"));	
FormDef formDef = fpi.getFormDef();
formDef.initialize(true, new InstanceInitializationFactory());

//cant get ref here!!
TreeReference reference = ((XPathPathExpr) XPathParseTool.parseXPath("/data/repeat[0]/option")).getReference();
FormIndex formIndex1 = getFormIndex(formDef, reference);

//this is possible though
FormIndex formIndex2 = scenario.indexOf("/data/repeat[0]/option");

//comes out fine if using formIndex2 from Scenario
FormEntryPrompt formEntryPrompt = new FormEntryPrompt(formDef, formIndex2);
List<SelectChoice> choices1 = formEntryPrompt.getSelectChoices();
```

fragment of the xml straight from xlsform from the original excel 
```
    <h:body>
        <group ref="/data/repeat">
            <label></label>
            <repeat jr:count=" /data/repeat_count " nodeset="/data/repeat">
                <select1 ref="/data/repeat/option">
                    <label>Select an option</label>
                    <itemset
                        nodeset="instance('options')/root/item[name = current()/. or not(selected(join(&quot; &quot;, /select-no-duplicates/repeat/option), name))]">
                        <value ref="name"/>
                        <label ref="label"/>
                    </itemset>
                </select1>
                <input ref="/data/repeat/question2">
                    <label>What do you think about<output value=" ../option "/>?
                    </label>
                </input>
            </repeat>
        </group>
    </h:body>
```

maybe shouldve asked this from the beginning :D
could you attach the xpath youre using and the classes youre invoking to get the stacktrace?

**Comment by lognaturel** [comment]
I realize that the test actually needs a fair amount of context so I put that together at https://github.com/getodk/javarosa/compare/master...lognaturel:issue-510. I simplified the predicate expression dramatically to just focus on demonstrating the failure. Hopefully this helps clear up what the problem is and gives you a reasonable place to start!

**Comment by abdulazizali77** [comment]
thanks @lognaturel will get to it!
